### ISSUE TITLE
Download the apk

### ISSUE THREAD

**Issue by Kcchouette** [xiprox/Hummingbird-for-Android#4]
Hello.

I found your project interesting.
Is there a way to test/download the apk project? (or even in a near future).

You can just host the apk in github, (for example).

Thanks

**Comment by xiprox** [comment]
Hello,

It's pretty unfinished so I didn't think posting an apk would benefit anyone. I can/will post one though.

**Comment by xiprox** [comment]
You can download the apk <a href="https://github.com/xiprox/Hummingbird-for-Android/releases/tag/v0.0.0">here</a>.

**Comment by Kcchouette** [comment]
:+1: thanks :)

**Comment by xiprox** [comment]
No issue! :)
