### ISSUE TITLE
Can't gradle the app

### ISSUE THREAD

**Issue by Kcchouette** [xiprox/Hummingbird-for-Android#5]
Hello, 
I can't gradle your project because of this error : 

Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command android-sdks\build-tools\21.1.1\aapt.exe'' finished with non-zero exit value 1`

Thanks

**Comment by xiprox** [comment]
Hello, it seems to be fine here. Can you try running it with build tools `21.1.2`?

**Comment by Kcchouette** [comment]
I'll try 21.1.2.

The only difference I have is on `build.gradle` L8 : `classpath 'com.android.tools.build:gradle:1.2.3'`

**Comment by xiprox** [comment]
Updated gradle version and getting the error here too. Will see if I can figure it out. In the worst case, you can use version `1.0.0` to build.

**Comment by xiprox** [comment]
It was caused by the ErrorView library. The problem was that the app was using an old `arr` version which included the `clould_off_large.png` and `ic_launcher.png` drawables. These drawables clashed with the ones that were already included in the app...
